defaults:
    - _self_
    # - ex: aspec.enja.baseline.100k
    - ex: aspec.enja.nfr.labse.enh100k_to_jah2m.top2.archi4
    # - ex: aspec.enja.nfr.labse.enh1m_to_jah2m.top1.archi0
    # - ex: debug2

do_train: True
do_eval: True
do_predict: True
